# Generated by Django 3.0.8 on 2020-07-06 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_auto_20200706_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='activity_periods',
            new_name='user',
        ),
    ]
